image: maven:3.9.9-eclipse-temurin-21-alpine

steps:
  - step: &build
      name: build
      caches:
        - maven
      script:
        - mvn clean package -DskipTests
      artifacts:
        - target/*.jar
  - step: &docker
      name: push docker
      caches:
        - docker
      script:
        - export DEPLOY_ENV=$BITBUCKET_BRANCH
        - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        - docker build -t $DOCKER_REPOSITORY/configserver-qt-$DEPLOY_ENV-1.0.0:$IMAGE_TAG .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REPOSITORY
        - docker push $DOCKER_REPOSITORY/configserver-qt-$DEPLOY_ENV-1.0.0:$IMAGE_TAG
      services:
        - docker
pipelines:
  pull-request:
    '**':
      - step: *build
  branches:
    main:
      - step: *build
      - step:
          <<: *docker
          deployment: Production
    develop:
      - step: *build
      - step:
          <<: *docker
          deployment: Staging
    staging:
      - step: *build
      - step:
          <<: *docker
          deployment: Staging